import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/Components/layout/NavBar/NavBar";
import Footer from "@/Components/layout/Footer/Footer";
import NextAuthProviders from "./Providers/NextAuthProviders";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthProviders>
          <NavBar />
          {children}
          <Footer />
        </NextAuthProviders>
      </body>
    </html>
  );
}
